exports.modules = [
  './MDBGulp/js/_intro-mdb-pro.js',
  './MDBGulp/js/vendor/jquery.easing.js',
  './MDBGulp/js/vendor/velocity.js',
  './MDBGulp/js/vendor/chart.js',
  './MDBGulp/js/vendor/wow.js',
  './MDBGulp/js/dist/scrolling-navbar.js',
  './MDBGulp/js/vendor/waves.js',
  './MDBGulp/js/dist/forms-free.js',
  './MDBGulp/js/dist/preloading.js',
  './MDBGulp/js/dist/cards.js',
  './MDBGulp/js/dist/character-counter.js',
  './MDBGulp/js/vendor/toastr.js',
  './MDBGulp/js/dist/smooth-scroll.js',
  './MDBGulp/js/dist/dropdown.js',
  './MDBGulp/js/dist/buttons.js',
  './MDBGulp/js/dist/sidenav.js',
  './MDBGulp/js/dist/collapsible.js',
  './MDBGulp/js/vendor/jquery.easypiechart.js',
  './MDBGulp/js/dist/range-input.js',
  './MDBGulp/js/dist/file-input.js',
  './MDBGulp/js/dist/material-select.js',
  './MDBGulp/js/vendor/picker.js',
  './MDBGulp/js/vendor/picker-date.js',
  './MDBGulp/js/vendor/picker-time.js',
  './MDBGulp/js/vendor/lightbox.js',
  './MDBGulp/js/dist/sticky.js',
  './MDBGulp/js/vendor/scrollbar.js',
  './MDBGulp/js/dist/chips.js',
  './MDBGulp/js/vendor/ofi.js',
  './MDBGulp/js/vendor/jarallax.js',
  './MDBGulp/js/vendor/jarallax-video.js',
  './MDBGulp/js/dist/mdb-autocomplete.js',
  './MDBGulp/js/vendor/enhanced-modals.js',
  // './MDBGulp/js/dist/treeview.js/',
  // // './MDBGulp/js/vendor/bs-custom-file-input.js/',
  // './MDBGulp/js/vendor/addons/jquery.zmd.hierarchical-display.js/',
  // './MDBGulp/js/vendor/addons/masonry.pkgd.min.js',
  // './MDBGulp/js/vendor/addons/imagesloaded.pkgd.min.js',
  // './MDBGulp/js/vendor/addons/datatables.js',
  // './MDBGulp/js/vendor/addons-pro/timeline.js',
  // './MDBGulp/js/vendor/addons-pro/steppers.js',
  // './MDBGulp/js/vendor/addons-pro/multi-range.js',
  // './MDBGulp/js/vendor/addons-pro/rating.js'
];
